// MOCKUP — illustrative sample-report content for the /automation/scan
// Step 4 view. The leading underscore makes the file invisible to the
// Next App Router (it is not a route segment).
//
// CLAUDE.md "Automation = mockup", review-guidelines.md "no fake
// 'success' presented as real": this content is NOT generated by any
// model. It is fixed prose chosen to illustrate the layout. The body
// copy contains "Beispiel-Report / Sample report" so the demo nature
// is preserved even if quoted out of context (worklog F-Q1).
import type { Locale } from '@/i18n/routing';

export type ReportTier = 'high' | 'mid' | 'long';

export interface ReportPotential {
  tier: ReportTier;
  title: string;
  what: string;
  effort: string;
  saving: string;
}

export interface DemoReport {
  section1: string;
  potentials: ReportPotential[];
  recommended: string;
  next: string;
  disclaimer: string;
}

export const DEMO_REPORT: { i18n: Record<Locale, DemoReport> } = {
  i18n: {
    de: {
      section1:
        'Beispiel-Report — illustrativer Inhalt. Auf Basis Ihrer Angaben wäre Ihr Betrieb ein typisches KMU mit gemischter Auftragsabwicklung und mehreren manuellen Übergängen zwischen E-Mail-Posteingang, ERP und Excel-Listen. Erfahrungsgemäss entstehen die grössten Reibungspunkte am Übergang zwischen Posteingang und ERP-System.',
      potentials: [
        {
          tier: 'high',
          title: 'Dokumentenverarbeitung',
          what: 'Rechnungen und Lieferscheine werden manuell ins ERP übertragen.',
          effort: 'Geschätzter Aufwand: ~8 h / Woche',
          saving: 'Mögliche Einsparung: 6–7 h / Woche durch KI-basierte Extraktion mit automatischem ERP-Import.',
        },
        {
          tier: 'high',
          title: 'Lieferanten-Follow-up',
          what: 'Status- und Terminanfragen werden per E-Mail verfolgt, ohne zentralen Überblick.',
          effort: 'Geschätzter Aufwand: ~4 h / Woche',
          saving: 'Mögliche Einsparung: 3 h / Woche durch automatisches Status-Tracking mit Eskalation.',
        },
        {
          tier: 'mid',
          title: 'Management-Reporting',
          what: 'KPIs werden monatlich aus mehreren Quellen manuell zusammengeführt.',
          effort: 'Geschätzter Aufwand: ~6 h / Monat',
          saving: 'Mögliche Einsparung: 5 h / Monat durch ein dünnes Dashboard auf bestehenden Datenquellen.',
        },
        {
          tier: 'long',
          title: 'Produktionsplanungs-Assistenz',
          what: 'Planung läuft im Kopf bzw. auf einem Whiteboard; KI-Assistenz wäre denkbar, lohnt sich aber erst nach den ersten Quick Wins.',
          effort: 'Geschätzter Aufwand: hoch',
          saving: 'Mögliche Einsparung: mittel-langfristig, abhängig von Datenqualität.',
        },
      ],
      recommended:
        'Basierend auf Ihren Angaben würde ich illustrativ empfehlen, mit der Dokumentenverarbeitung zu starten. Sie liefert den schnellsten ROI bei geringstem Risiko. Geschätzter Aufwand: 2–3 Wochen · Geschätzte Kosten: CHF 5\'000–8\'000 · Geschätzte Einsparung: ~6 h / Woche ≈ CHF 18\'000 / Jahr.',
      next:
        'Dieser Report ist ein Beispiel. Für eine echte, persönliche Analyse — inklusive Branchenrecherche und konkretem Massnahmenplan — buchen Sie ein unverbindliches Erstgespräch oder fordern Sie eine vertiefte Analyse an. Lieferzeit: 1–2 Arbeitstage. Kosten: kostenlos (Teil meines Angebots).',
      disclaimer:
        'Diese Analyse ist ein Beispiel und basiert auf Demo-Eingaben. Sie ersetzt keine detaillierte Vor-Ort-Analyse. Die geschätzten Einsparungen sind Richtwerte.',
    },
    en: {
      section1:
        'Sample report — illustrative content. Based on your answers your company would be a typical SME with mixed order intake and several manual hops between email inbox, ERP and Excel sheets. The biggest friction usually sits at the handover between the inbox and the ERP.',
      potentials: [
        {
          tier: 'high',
          title: 'Document processing',
          what: 'Invoices and delivery notes are typed into the ERP by hand.',
          effort: 'Estimated effort: ~8 h / week',
          saving: 'Possible saving: 6–7 h / week via AI-based extraction with automatic ERP import.',
        },
        {
          tier: 'high',
          title: 'Supplier follow-up',
          what: 'Status and deadline requests are tracked over email without a central overview.',
          effort: 'Estimated effort: ~4 h / week',
          saving: 'Possible saving: 3 h / week via automated status tracking with escalation.',
        },
        {
          tier: 'mid',
          title: 'Management reporting',
          what: 'KPIs are pulled together manually from several sources every month.',
          effort: 'Estimated effort: ~6 h / month',
          saving: 'Possible saving: 5 h / month via a thin dashboard over the existing data sources.',
        },
        {
          tier: 'long',
          title: 'Production-planning assistant',
          what: 'Planning lives in someone\'s head or on a whiteboard; AI assistance is feasible but pays off only after the early quick wins.',
          effort: 'Estimated effort: high',
          saving: 'Possible saving: medium-to-long term, depending on data quality.',
        },
      ],
      recommended:
        "Based on your answers I would illustratively suggest starting with document processing. It delivers the fastest ROI at the lowest risk. Estimated effort: 2–3 weeks · estimated cost: CHF 5,000–8,000 · estimated saving: ~6 h / week ≈ CHF 18,000 / year.",
      next:
        'This report is an example. For a real, personal analysis — including industry research and a concrete action plan — book a no-strings call or request a deep-dive analysis. Turnaround: 1–2 working days. Cost: free (part of my offering).',
      disclaimer:
        'This analysis is an example and is based on demo input. It does not replace a detailed on-site review. The estimated savings are guideline figures.',
    },
  },
};
